# RBAC setup for OpenTelemetry Collectors
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: tempo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: ["tempo.grafana.com"]
    resources: ["dev", "prod"]
    resourceNames: ["traces"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: tempo