apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
 name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      otlp:
        endpoint: tempo-prod-distributor:4317
        tls:
          insecure: true
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
