apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: tempo-stack
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  config: |
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    
    connectors:
      spanmetrics:
        metrics_flush_interval: 15s
        
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
        send_batch_max_size: 2048
      
      resource:
        attributes:
          - key: service.namespace
            value: tempo-stack
            action: upsert
    
    exporters:
      # Debug exporter for troubleshooting
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      
      # Option 1: OTLP HTTP exporter (standard port)
      otlphttp:
        endpoint: http://tempo-prod-distributor:4318
        headers:
          X-Scope-OrgID: petclinic
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
      
      # Prometheus exporter for span metrics
      prometheus:
        endpoint: 0.0.0.0:8889
        add_metric_suffixes: false
        resource_to_telemetry_conversion:
          enabled: true
    
    service:
      telemetry:
        logs:
          level: debug
        metrics:
          address: 0.0.0.0:8888
          level: detailed
      
      extensions:
        - bearertokenauth
      
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug, otlphttp, spanmetrics]
        
        metrics:
          receivers: [spanmetrics]
          processors: [batch]
          exporters: [prometheus]