apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      annotations:
        instrumentation.opentelemetry.io/inject-java: petclinic
    spec:
      containers:
      - image: springcommunity/spring-framework-petclinic:6.0.3
        name: petclinic
