#Applied

apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
spec:
  storage:
    secret:
      name: odf-tempo
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  tenants:
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa" #CHANGE
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: false 
