apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
 name: prod
spec:
 storage:
   secret:
     name: odf-tempo
     type: s3
 storageSize: 1Gi
 template:
   queryFrontend:
     jaegerQuery:
       enabled: true
       monitorTab:
         enabled: true
         prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
         
       ingress:
         type: route
